Controllers/CharacterController.cs
using Gobln.Pager;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using WebApplication1.Models;
using WebApplication1.rickandmortyapi;

namespace WebApplication1.Controllers
{
    public class CharacterController : Controller
    {
        public async Task< IActionResult> Index(int page = 1)
        {


            ViewBag.page = page;

            ApiCall apicall = new ApiCall();
            var call = apicall.GetApiresult(string.Format("api/character?page={0}", page) );
            string result = await call.Content.ReadAsStringAsync();

            Character response = JsonSerializer.Deserialize<Character>(result);

            ViewBag.pages = response.info.pages;

            return View(response);
        }
        public async Task<IActionResult> show(int id)
        {
            ApiCall apicall = new ApiCall();
            var call = apicall.GetApiresult(String.Format("api/character/{0}",id) );
            string result = await call.Content.ReadAsStringAsync();


            CharacterResult response = JsonSerializer.Deserialize<CharacterResult>(result);

            return View(response);
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;
using System.Text.Json; 
using System.Text.Json.Serialization;

namespace WebApplication1.Controllers
{


    using System;
    using System.Collections;
    using System.Net.Http.Headers;
    using WebApplication1.rickandmortyapi;

    public class HomeController : Controller
    {        
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

        }
        public async  Task<ActionResult> Index()
        {
        ApiCall apiCall = new ApiCall();

        HttpResponseMessage apiResultCharacter = apiCall.GetApiresult("/api/character");
        var messageCharacter  = await apiResultCharacter.Content.ReadAsStringAsync();

        HttpResponseMessage apiResultLocation = apiCall.GetApiresult("/api/location");
        var messagelocation = await apiResultLocation.Content.ReadAsStringAsync();

        HttpResponseMessage apiResultEpisode = apiCall.GetApiresult("/api/episode");
        var messageEpisode = await apiResultEpisode.Content.ReadAsStringAsync();



        Character characters = JsonSerializer.Deserialize<Character>(messageCharacter);
        location location = JsonSerializer.Deserialize<location>(messagelocation);
        Episode episode = JsonSerializer.Deserialize<Episode>(messageEpisode);



            var CharacterLocationEpisodeViewModel = new CharacterLocationEpisodeViewModel()
            {
                Characters = characters,
                location = location,
                episode = episode
            };



            return View(CharacterLocationEpisodeViewModel);
           

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;
using WebApplication1.rickandmortyapi;

namespace WebApplication1.Controllers
{
    public class LocationController : Controller
    {
        public async Task<IActionResult> Index()
        {
            ApiCall apiCall = new ApiCall();

            HttpResponseMessage apiResultCharacter = apiCall.GetApiresult("/api/location");
            var messageLocation = await apiResultCharacter.Content.ReadAsStringAsync();

            location location = JsonSerializer.Deserialize<location>(messageLocation);


            return View(location);
        }
        public async Task<IActionResult> Show(string url)
        {
            var apiCall = new ApiCall();

            HttpResponseMessage apiResultEpisode = apiCall.GetApiresult(url);
            var characterLocationMessages = await apiResultEpisode.Content.ReadAsStringAsync();
            locationResult characterLocation = JsonSerializer.Deserialize<locationResult>(characterLocationMessages);

            List<CharacterResult> CharacterResult = new List<CharacterResult>();

            foreach (var character in characterLocation.residents)
            {
                HttpResponseMessage apiResultCharacter = apiCall.GetApiresult(character.ToString());
                var characterMessages = await apiResultCharacter.Content.ReadAsStringAsync();
                var response = JsonSerializer.Deserialize<CharacterResult>(characterMessages);
                CharacterResult.Add(response);
            }

            CharacterLocationViewModel characterLocationViewModel = new CharacterLocationViewModel
            {
                characterresult = CharacterResult,
                locationResult = characterLocation,
            };

            return View(characterLocationViewModel);
        }

    }
}

Views/Home/Index.cshtml
@using WebApplication1.Models.ViewModels
@model CharacterLocationEpisodeViewModel

<header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->

                <i class="fa-solid fa-laptop-code masthead-avatar mb-5"></i>
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">The Rick and Morty API</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
            </div>
        </header>
        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Characters</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row text-center">

                    @foreach(var characters in Model.Characters.results.Take(6))
                    {
                        <div class="col-sm-4 col-md-4 col-12  p-1 ">
                            
                                <div class="card">
                                    <img class="card-img-top" src="@characters.image" alt="Card image cap">
                                    <div class="card-body">
                                    <h5 class="card-title">@characters.name</h5>
                                    <p class="card-text">his species is: @characters.species</p>
                                    <a asp-action="show" asp-controller="Character" asp-route-id="@characters.id">show character info</a><br><br/>
                                    <a asp-action="show" asp-controller="Location" asp-route-url="@characters.location.url" >last knonw location is @characters.location.name</a>
                                    </div>                                    
                                </div>
                        </div>
                    }
                </div>
                <a asp-controller="Character" asp-action"index" >see more characters</a>

            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">location</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                 
                <!-- location section -->
                 <div class="row text-center">

                    @foreach(var location in Model.location.results.Take(6))
                    {
                        <div class="col-sm-4 col-md-4 col-12  p-1 ">
                                <div class="card text-black">
                                    <div class="card-body">
                                    <h5 class="card-title">@location.name</h5>
                                    <p class="card-text">this location has : @location.residents.Count() residents</p>
                                    <a asp-action="show" asp-controller="Location" asp-route-url="@location.url" class="">check this location out</a>
                                    </div>                                    
                                </div>
                        </div>
                    }
                </div>
                <!-- location end-section -->

                
            </div>
        </section>
        <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                     <!-- episode section -->
                 <div class="row text-center">

                    @foreach(var episode in Model.episode.results.Take(6))
                    {
                        <div class="col-sm-4 col-md-4 col-12  p-1 ">
                     
                                <div class="card">
                                    <div class="card-body">
                                    <h5 class="card-title">@episode.name</h5>
                                    <p class="card-text">Aired on : @episode.air_date</p>
                                    <a asp-action="show" asp-controller="episode" asp-route-id="@episode.id">check this episode out </a>                                  

                                    </div>                                    
                                </div>
                        </div>
                    }
                </div>
                <!-- epide end-section -->
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center  pb-0 mb-0">
            
        </footer>